[package]
name = "mcr"
version = "0.1.0"
authors = ["Curtis Ruck <curtis@ruck.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.14.1"
log = "0.4.8"
hexdump = "0.1.0"
zerocopy = "0.2.7"